### ISSUE TITLE
Install roxygen2

### ISSUE THREAD

**Issue by krlmlr** [wch/r-debug#3]
This is currently necessary to run `devtools::test()` and `devtools::run_examples()`. I can do a PR.

**Comment by wch** [comment]
Sure, that makes sense. Maybe it should be installed in `/usr/local/RD/lib/R/library` so that it doesn't need to be installed for each build of R?

Now that I think about it, a number of other utility packages (ones that don't contain compiled code) should probably be installed there. For example, BH is large and commonly used, but doesn't have any compiled code, so it would make sense to share it. You don't have to do this part, but you can if you feel like doing it.

**Comment by wch** [comment]
Fixed in 0fb2002.
